@URL=https://dns.google/resolve

GET {{URL}}
  ?name={{VITE_DOMAIN}}
  &type=a

GET {{URL}}
  ?name=www.{{VITE_DOMAIN}}
  &type=cname

GET {{URL}}
  ?name={{VITE_DOMAIN}}
  &type=txt

GET {{URL}}
  ?name=_dmarc.{{VITE_DOMAIN}}
  &type=txt

GET {{URL}}
  ?name={{VITE_DOMAIN}}
  &type=mx

GET {{URL}}
  ?name={{VITE_DOMAIN}}
  &type=aaaa