# @import ./variables.http

GET {{DNS_API_URL}}
  ?name={{ACTIVE_DOMAIN}}
  &type=a
// A request

###
# @import ./variables.http

GET {{DNS_API_URL}}
  ?name=www.{{ACTIVE_DOMAIN}}
  &type=cname
 // CNAME request for www

###
# @import ./variables.http

GET {{DNS_API_URL}}
  ?name={{ACTIVE_DOMAIN}}
  &type=txt
// TXT request

###
# @import ./variables.http

GET {{DNS_API_URL}}
  ?name=_dmarc.{{ACTIVE_DOMAIN}}
  &type=txt
// TXT request for _dmarc

###
# @import ./variables.http

GET {{DNS_API_URL}}
  ?name={{ACTIVE_DOMAIN}}
  &type=mx
// MX request

###
# @import ./variables.http

GET {{DNS_API_URL}}
  ?name={{ACTIVE_DOMAIN}}
  &type=aaaa
// AAAA request
