@URL=https://dns.google/resolve
@DOMAIN={{VITE_DOMAIN}}

GET {{URL}}
  ?name={{DOMAIN}}
  &type=a
// A request

GET {{URL}}
  ?name=www.{{DOMAIN}}
  &type=cname
 // CNAME request for www

GET {{URL}}
  ?name={{DOMAIN}}
  &type=txt
// TXT request

GET {{URL}}
  ?name=_dmarc.{{DOMAIN}}
  &type=txt
// TXT request for _dmarc

GET {{URL}}
  ?name={{DOMAIN}}
  &type=mx
// MX request

GET {{URL}}
  ?name={{DOMAIN}}
  &type=aaaa
// AAAA request
