# @import ./variables.http

GET {{WHOIS_API_URL}}
  ?domain={{ACTIVE_DOMAIN}}
  apikey:{{WHOIS_API_KEY}}
// WhoIS request with an active domain name

###
# @import ./variables.http

GET {{WHOIS_API_URL}}
  ?domain={{MISSPELLED_DOMAIN}}
  apikey:{{WHOIS_API_KEY}}
// WhoIS request with a misspelled domain name


###
# @import ./variables.http

GET {{WHOIS_API_URL}}
  ?domain=random.co.uk
  apikey:{{WHOIS_API_KEY}}
