@URL=https://api.apilayer.com/whois/query
@MISSPELLED_DOMAIN=nikola-nenovasasdki.info
@CORRECT_DOMAIN={{VITE_DOMAIN}}
@API_KEY={{VITE_API_KEY}}

GET {{URL}}
  ?domain={{MISSPELLED_DOMAIN}}
  apikey:{{API_KEY}}
// WhoIS request with a misspelled domain name

GET {{URL}}
  ?domain={{CORRECT_DOMAIN}}
  apikey:{{API_KEY}}
// WhoIS request with an active domain name