# @import ./variables.http
GET {{ WORKER_API_URL }}/dns?domain={{ ACTIVE_DOMAIN }}
// Sending a valid request with an active domain

###
# @import ./variables.http
GET {{ WORKER_API_URL }}/whois?domain=adadassssa.com
// Sending a request with an inactive domain

###
# @import ./variables.http
GET {{ WORKER_API_URL }}/whois?domain=nickslabcode.com
// Sending a request with an expired domain name

###
# @import ./variables.http
GET {{ WORKER_API_URL }}/whois?domain=abv.bg
// Sending a request with an domain name from a reseller

###
GET http://localhost:8787/wp-check?domain=mrtnbdrv.com

###
GET http://localhost:8787/whois?domain=nikola-nenovski.com

###
GET http://localhost:8787/cdn-check?domain=cexposurefilms.com

###

GET https://api.github.com/repos/Nickslabcode/domain-info-lookup/releases

###
# @import ./variables.http
GET {{ WORKER_API_URL }}/wp-check?domain=mrtnbdrv.com

###
# @import ./variables.http
GET {{ WORKER_API_URL }}/wp-check?domain=nikola-nenovski.com

###

GET https://o2h83alxd2.execute-api.eu-central-1.amazonaws.com/api/v1/wp-check?domain=cexposurefilms.com