# @import ./variables.http
GET {{ WORKER_API_URL }}/{{ ACTIVE_DOMAIN }}
// Sending a valid request with an active domain

###
# @import ./variables.http
GET {{ WORKER_API_URL }}
// Sending a request without a domain

###
GET http://localhost:8787/whois?domain=nikola-nenovski.info